### ISSUE TITLE
Publish 4.5.0 to maven central

### ISSUE THREAD

**Issue by luca-domenichini** [dotxyteam/ReflectionUI#1]
Hello,
as of 2018-12-13, I noticed that 4.5.0 available here http://javacollection.net/reflectionui/downloads-directory/, but is not published to maven central (the latest is 4.2.0).

Could you update it please?

**Comment by dotxyteam** [comment]
Hello,

reflection-ui 4.5.0 can be published but not custom-ui 4.5.0. It would not be very useful to you i guess.
This is for technical reasons (group id will be rejected by sonatype).
It will be fixed for the next release (probably 4.5.2). For now you should just install them to your local repo.

Regards
